import Head from 'next/head'  
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import axios from "axios";

function Dogs({ imglink }) {
  return <img className={styles.dogImage} alt="" src={imglink.message} width={500} height={500}/>
}

export default function Home() {
  const [dogImage, setDogImage] = useState(null);
  const [reTitle, setReTitle] = useState("Klik untuk gambar anjing");

  const fetchData = async (e) => {
    e.preventDefault();
    setDogImage(null)
    const url = `https://dog.ceo/api/breeds/image/random`;
    let data = await axios.get(url);
    setDogImage(data.data)
    setReTitle("Klik untuk melihat gambar lain")
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.titleScreen}>Random Dog Image</h1>
        <button className={styles.buttonDog} onClick={fetchData}>{reTitle}</button>
        { dogImage && <Dogs imglink={dogImage} ></Dogs>}
      </main>
    </>
  )
}
